sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t diegomattozo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true diegomattozo/docker-react npm run test

